### ISSUE TITLE
Style switcher: selection isn't stored for current session

### ISSUE THREAD

**Issue by RAeschimann** [RAeschimann/project-notes#2]
store selection from style switcher into the browser session storage

**Comment by uenala** [comment]
session now stores current style selection.

**Comment by uenala** [comment]
Data stored in the sessionStorage object is shared only with pages from the same domain opened in the same window/tab and does not persist after the window/tab is closed. Every time a user opens a page in a new window/tab, the browser creates a new session storage database.

**Comment by RAeschimann** [comment]
After a refresh the style dropdown isn't update with the stored style.
Another Improvement: apply stored style on edit pages as well.

**Comment by uenala** [comment]
The problem occurs after editing a note (or adding a new note) and coming back to the index page: the style dropdown gets initialized on "default" even if the current style is not default.
