### ISSUE TITLE
Implement sorting notes by importance.

### ISSUE THREAD

**Issue by uenala** [RAeschimann/project-notes#6]
The most Important note (Priority 5?) should be on top of the list after sorting.

**Comment by uenala** [comment]
current solution: createSortableArrayOfJSON() converts the JSON-Object of localStorage to an array. The array is easier to sort. sortNotesByPriority() then sorts the array, updates localStorage with the sorted data and renders the notes.

**Comment by RAeschimann** [comment]
After converting the data structure to an array in localStorage  the creation date (until now the object key) get lost and several function based on this key don't work anymore. Either the data model has to be changed for the whole project or an other method for sorting has to be implemented, e.g. sorting li items with JQuery.
